targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**.dart
          - !lib/features/sales/presentation/widgets/payment_section.dart
      injectable:injectable_builder:
        generate_for:
          - lib/**.dart
          - !lib/features/sales/presentation/widgets/payment_section.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/**.dart
          - !lib/features/sales/presentation/widgets/payment_section.dart
      json_serializable:
        generate_for:
          - lib/**.dart
          - !lib/features/sales/presentation/widgets/payment_section.dart
