name: cashier_pos
description: "A point of sale application for managing sales, inventory, and customers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Dependencies
  get_it: ^7.6.7
  injectable: ^2.1.2
  intl: ^0.20.2  # Must be compatible with flutter_localizations
  logger: ^2.0.2
  uuid: ^4.3.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Database
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Network
  internet_connection_checker: ^1.0.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.10+1
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.4.7
  injectable_generator: ^2.1.5
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_test:
    sdk: flutter

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
